### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [MedAlexey/Cut#1]
1. Правильнее было бы вынести всю функциональность, связанную с разбором аргументов командной строки в отдельный класс (лучше отдельный от главного класса), который предоставляет удобный интерфейс для получения аргументов. Чтобы после создания объекта с разобранными аргументами можно было получить любой параметр запуска с помощью геттеров:
```java
int startPosition = cmdLine.getStartPosition()
int endPosition = cmdLine.getEndPosition()
String filename = cmdLine.getFilename()
```
2. Почитайте про систему ввода/вывода в Java (например, 5 лекция курса) и подумайте, как организовать ввод/вывод универсально для файла и консоли.
3. Из входного потока нужно считывать строки до тех пор, пока в нём не закончаться данные, а не до считывания пустой строки (т. е. до тех пор, пока `read()` не вернёт -1 или readLine() - `null`). Проверить работу с консолью в таком режиме можно двумя способами:
    i. Нажатие `Ctrl-D` приведёт к завершению входного потока.
    ii. Можно протестировать вашу программу, применив её к выводу другой программы, например набрав в консоли:
    ```
    type c:\path\to\some\file.txt | java -jar Cut.jar <ваши опции>
    ```
    Эта команда выведет содержимое файла и передаст его в вашу программу через стандартный поток ввода. Это, на самом деле, и является основным usecase консольного режима (как и в большинстве стандартных консольных утилит). В связи с этим "отвечать" на ввод можно построчно.
4. Передавать режим работы между функциями в виде символа (`c` или `w`) - очень плохой стиль. В функции `lineHandling` просто две отдельных ветки (возникает вопрос, почему это не две отдельных функции). Попробуйте решить эту проблему в объектно-ориентированном стиле (интерфейс `LineHandler` с методом `handleLine` и две его реализации). Вместо `c` или `w` передавайте объект `LineHandler`.

**Comment by MedAlexey** [comment]
@gagarski замечания исправлены

**Comment by gagarski** [comment]
1. В классе `CmdLine` вы используете изменяемые статические поля, что является плохим стилем. Более того, вы заполняете их из конструктора этого класса, что совсем странно. Почему бы не сделать эти поля (и геттеры для них) нестатическими и в классе `Cut` использовать объект этого класса.
2. С функцией `printing` и параметром `outputStream` вы всё сделали примерно правильно, но в коде чтения из входного потока видно дублирование кода. Можно ли сначала создать выходной поток (консольный или файловый), а затем читать из него.
3. Для ввода/вывода строк попробуйте поменять `Stream`'ы на `BufferedReader`/`BufferedWriter`, у них есть методы для чтения/записи строк.

**Comment by MedAlexey** [comment]
@gagarski замечания исправлены
